[project]
name = "pytest-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bohdan Parkulab", email = "parkulab.bohdan.98@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pytest-playground = "pytest_playground:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
